name: ImageEmojis-Bero
version: '${project.version}'
main: mrquackduck.imageemojis.ImageEmojisPlugin
api-version: '1.19'
authors: ['MrQuackDuck', 'Bero_A']
description: "ImageEmojis 플러그인에 부가 기능을 추가했어요."
website: "https://github.com/Bero-a/ImageEmojis-Bero"
depend: [ ProtocolLib ]

commands:
  emojis:
    description: Image Emojis command
    permission: imageemojis.use
    aliases:
      - ie
      - imageemojis

permissions:
  imageemojis.admin:
    description: Allows a player to reload the plugin
    default: op
  imageemojis.update:
    description: Whether a player can fetch the latest version of the resource pack during current session
    default: true
  imageemojis.list:
    description: Whether a player can open a book with all emojis
    default: true
  imageemojis.use:
    description: Whether a player can use emojis and "/emojis" command
    default: true